version: '2'

services:
  gitserver:
    image: gogs/gogs:latest
    ports:
      - "22:22"
      - "3000:3000"
    networks:
      - forge
    volumes:
      - git-data:/data
      - ./docker/gogs/app.ini:/data/gogs/conf/app.ini
  gitserver-config:
    build: ./docker/gitserver-config/
    volumes:
      - ./:/current_data
    networks:
      - forge
    depends_on:
      - gitserver

  jenkins2:
    image: jenkins:2.7.1
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JENKINS_SLAVE_AGENT_PORT=50000
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins2-data:/var/jenkins_home
      - ./plugins:/usr/share/jenkins/ref/plugins/
      - ./sshkeys:/custom-ssh-keys
    networks:
      - forge
  # 
  # build-agent:
  #   build:
  #     context: ./docker/jenkins-agents/
  #     dockerfile: Dockerfile-build
  #   networks:
  #     - forge
  #   restart: unless-stopped
  #   depends_on:
  #     - jenkins2
  #   environment:
  #     - JENKINS_URL=http://jenkins2:8080
  #     - NODE_NAME=build-agent
  #     - NODE_LABELS=maven3 jdk8 maven3-jdk8
  #
  # docker-agent:
  #   build:
  #     context: ./docker/jenkins-agents/
  #     dockerfile: Dockerfile-docker
  #   networks:
  #     - forge
  #   restart: unless-stopped
  #   depends_on:
  #     - jenkins2
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - JENKINS_URL=http://jenkins2:8080
  #     - NODE_NAME=docker-agent
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #     - NODE_LABELS=docker
  #
  # local-docker-registry:
  #   image: registry:2
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - docker-reg-data:/var/lib/registry
  #   networks:
  #     - forge
  #
  # artefactserver:
  #   image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:latest
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - ./host-m2-repo:/shared-m2-repository
  #   networks:
  #     - forge
  #
  # artefactserver-config:
  #   build: ./docker/artefactserver-config/
  #   restart: on-failure:10
  #   depends_on:
  #     - artefactserver
  #   networks:
  #     - forge
  #   environment:
  #     - SHARED_M2_REPOSITORY=/shared-m2-repository
  #     - ARTEFACT_SERVER_URL=http://artefactserver:8081

volumes:
  git-data:
  shared-m2:
  docker-reg-data:
  jenkins1-data:
  jenkins2-data:

networks:
  forge:
